<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\RiotSharp.Account\RiotSharp.Account.csproj" />
    <ProjectReference Include="..\RiotSharp.Core\RiotSharp.Core.csproj" />
    <ProjectReference Include="..\RiotSharp.LeagueOfLegends\RiotSharp.LeagueOfLegends.csproj" />
  </ItemGroup>

</Project>
