<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <None Include="Endpoints\ActiveRegion.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AV.RiotSharp.Core" Version="0.1.0" />
  </ItemGroup>

</Project>
