# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net
name: .NET

on:
  push:
    branches: ["refactor"]
  pull_request:
    branches: ["refactor"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
          cache: true

      - name: Restore dependencies
        run: dotnet restore src/RiotSharp.sln

      - name: Build
        run: dotnet build src/RiotSharp.sln --no-restore --configuration Release

      - name: Test
        run: dotnet test src/RiotSharp.sln --no-build --configuration Release --verbosity normal -e API_KEY=${{secrets.RIOT_API_KEY}} #--filter "Category!=OnlyLocal"
